### PR TITLE
Fix grunt peer dep

### PR DESCRIPTION
**Pull request by jmalonzo**

### CODE REVIEW

**Review by julkue — APPROVED** [review]
@nfroidure Can you please merge this asap?

**Comment by poppinlp** [comment]
@julmot  Sry i forgot this. My bad.

**Comment by julkue** [comment]
@poppinlp Thanks. Please don't forge to publish [a new version to npm](https://www.npmjs.com/package/grunt-ttf2woff). Otherwise we won't receive the update.

**Comment by poppinlp** [comment]
@julmot  Yep. Already published. And thanks for remind this RP :)

**Pull request merged**
